### ISSUE TITLE
Database get compressed - takes a long time

### ISSUE THREAD

**Issue by CvH** [MediaBrowser/plugin.video.emby#126]
Hi, I am using Kodi LE8.2.x (latest Kodi17 + latest Emby) and getting suspicious timeouts after watching movies/shows at several devices (problem exist at least 1/4 year).

After a movie/show is finished (every 2-4 movies/episodes) there is a notification "database get compressed" - that locks the entire gui for several seconds. I am not sure what it does nor from where it comes from.

log with the entry for that operation 
`NOTICE: VideoInfoScanner: Finished scan. Scanning for video info took 00:41`
https://pastebin.com/SciV8kTb

There are no obvious speed limits anywhere (LAN/eMMC/NAS) so I have no real idea where to search for it. Any help to debug this is  appreciated.

**Comment by CWGSM3V0** [comment]
I've seen this as well - no apparent rhyme or reason to it. If I re-select the title again, most of the time it'll play, sometimes it'll continue to timeout until I reboot.

**Comment by angelblue05** [comment]
I know this issue was open a while ago. That is nothing to do with the add-on itself. You need to go in the Kodi settings > media settings > Hide progress for library updates. In emby beta 3.1+ I've made some changes to the way we interact with the database, which should also help with the situation.
