### ISSUE TITLE
Feature Request: Add a quiet option

### ISSUE THREAD

**Issue by hpmueller1971** [MediaBrowser/plugin.video.emby#151]
Hi, please, pretty please, add a quiet option to disable the popups ("You have 1652 updates, doing full sync in the library sync menu would be faster"), basically like the old version behaves, unless opening the app, a user should not be intererupted, and the addon should not "decide" to interrupt syncing just to ask something. A full server refresh can take a long time, so im running the emby-server-tasks at night - just to find in the morning, that my kodis are waiting for me to click ok...

(sorry, english isn't my native language, i dont want to be rude, even if it probably sounds like it. The behavior of the old version was fine for me, i reverted to Kodi17 with emby-plugin 3.0.34a and i will probably stay on that until this is is "fixed", even if the new version seems to be much "snappier". But the interruptions are pretty much a showstopper)

**Comment by anoma** [comment]
I believe you can set a value for when the popup kicks in from the addon settings.

I like the idea of this feature but ideally it needs to be smarter e.g. suggesting it may be faster to reload dbase of 10k entries for 200 updates is never going to be true.

**Comment by angelblue05** [comment]
It does say may, because you control this. Reload the database? It simply says to update the library in favor of this. Mostly because, pulling one item at a time, depending on your server, connection, etc. may be slower than pulling items in bulk when updating the library (since you can select which library to update).

@hpmueller1971 
You can control the value at which it pops up. In the add-on settings > sync options. Enable notification if update count is greater than.

**Comment by anoma** [comment]
I haven't done it yet but I plan to try and bypass the feature because it is causing problems with the kids. 

They are simply not capable of following this dialogues through to completion and cant handle the 30 min wait a full reload takes anyway.
