### ISSUE TITLE
Backup/restore and a means for designating one client as master to fast sync others

### ISSUE THREAD

**Issue by nomandera** [MediaBrowser/plugin.video.emby#354]
I covered this before in direct chat but to summarise.

If you have multiple devices and multiple users in your home, (which is a likely scenario given the nature of users wanting a central Emby store), it is impractical and time consuming to maintain sync unless you have high-end clients.

For example using AMLogic LibreELEC installs for a family of four plus a guest each device takes me 14 hours of sync time to reset the Kodi database (with me requiring to be in front of the screen on five separate occasions per device).

Note: _Over time Kodi and Emby get out of sync. Its i small but its enough to make this a non optional requirement currently._

To work around this I migrated to all identical hardware, designate one device as master, sync this with Emby and then use rsync to maintain all other devices.

This approach drops the sync time for all subsequent nodes from 14 hours to 60 seconds using a single command.

My approach whilst fast is a kludge and cannot handle hardware, config or addon differences between nodes.

At its core though the idea is sound and it is theoretically possible (perhaps even quite easy) to have the Emby sync addon designate one node as master and maintain backups of key data in one location such as a shared drive. This opens the door for per profile backup and restore regardless of platform or addon collection. The systems would need to be on the same Kodi version but not much else would matter.

With this feature one fast machine such as a desktop PC could be designated master making even the lowest end clients "fast" to rebuild and it goes without saying backups of this sort are good to have regardless.

**Comment by quickmic** [comment]
> Note: Over time Kodi and Emby get out of sync. Its i small but its enough to make this a non optional requirement currently.
This hsould be already fixed in 4.1.21
#353 

Actually where is a backup function in E4K plugin available but not sure if it works at the moment and it's not designed for inter Device sync.
Actually, I also use quick often backups from one device to another but manually.
I think different hardware is no problem at all cause only the settings should be transfered between devices.
What files are you syncing via rsync?
Under the premises, same emby4kodi addon version and emby4kodi is configured but just not synced with server, following files are critical:

kodi/userdata/Database/MyVideos* -> currently kodi/userdata/Database/MyVideos116.db
kodi/userdata/Database/MyMusic* -> currently kodi/userdata/Database/MyMusic72.db
kodi/userdata/Database/emby.db
kodi/userdata/Database/Textures* -> currently kodi/userdata/Database/Textures13.db (optional)
kodi/userdata/Thumbnails/* (optional)
kodi/userdata/addon_data/plugin.video.emby/sync.json

I'll check the current backup function and see if I can offer two options. Something like interdevice backup and full backup.

**Comment by anoma** [comment]
These are not pretty and very LibreELEC centric but its shows the basic premise. 

One plus point is that it handles Kodi multiuser e.g.

```
~/.kodi/userdata/profiles/guest # ls
Database         addon_data       favourites.xml   guisettings.xml  keymaps          library          playlists        sources.xml
```


```
#!/usr/bin/bash
# This script copies the contents of storage on the master Kodi Emby node to the NAS for backup and later propegation to new machines
# It must only be run on master Kodi Emby node

#Stop Kodi
systemctl stop kodi

#Upload master copy to backup server
rsync -Pav --delete -e "ssh -p 22 " --exclude '*.log' /storage/ rsync@server:/mnt/cache/.kodi-emby/storage-master/

#Start Kodi
systemctl start kodi
```

```
#!/usr/bin/bash
# This script copies the  master Kodi Emby node data from the NAS to the local LibreELEC install
#This will OBLITERATE the existing install data so use with CAUTION

#Stop Kodi
systemctl stop kodi

#Update slave copy. DO NOT RUN ON MASTER NODE.
rsync --delete -Pav --exclude=".cache" --exclude="oe_settings.xml" --exclude="emby_guid" -e "ssh -p 22 " rsync@server:/mnt/cache/.kodi-emby/storage-master/ /storage/

#Start Kodi
systemctl start kodi
```

**Comment by anoma** [comment]
I spent quite a bit of time proving this concept yesterday based on all the notes so far.

I succesfully used a fast x86 instance I designated master to update a single user profile on a designated slave slow AMLogic node. This is a milestone for me.

Obviously an native addon that doesn't require killing Kodi from the command line and is aware of potential database version clashes would be better but at least now I have the start of something working.

Once I am sure it is OK I will post my notes but at its core it is just a few simple but very specific rsync commands to replicate your steps posted above @quickmic

**Comment by quickmic** [comment]
Thanks, I'll review it as soon as I have a some time left.
At the moment, I focus on Kodi Matrix updates and some other critical issues first before I implement additional features.

**Comment by anoma** [comment]
Just to follow up on this. I am now successfully using the following script to backup just the files needed to allow for copying profiles to other devices. I dont claim that is pretty or perfect but it appears to work well and is architecture agnostic allowing me to use a fast machine when rebuilding data for a slow machine.


```
#!/usr/bin/bash
# Backup Emby for Kodi addon data for all local Kodi user profiles.
# We intentionally exclude the default non profile Kodi user.
# LibreELEC proof of concept.

# Stop Kodi
systemctl stop kodi

# Kodi master profile list
rsync -Pav --delete /storage/.kodi/userdata/profiles.xml /storage/backup/userdata/

# Thumbnails (Optional)
#rsync -Pav --delete /storage/.kodi/userdata/Thumbnails/ /storage/backup/userdata/

# Profile library databases and Emby for Kodi sync config
rsync -Pav --prune-empty-dirs --delete \
        --include='*/' \
        --include='*Database*/MyVideos*' \
        --include='*Database*/MyMusic*' \
        --include='*Database*/Textures*' \
        --include='*Database*/emby.db' \
        --include='sync.json' \
        --exclude='*'  \
        /storage/.kodi/userdata/profiles/ /storage/backup/userdata/profiles/

# Restart Kodi
systemctl start kodi
```
There is a script for the restore section of this but I hold it back because it is really dangerous and very LibreELEC specific.

The main point though is that `this all just works` and is extremely useful even as a proof of concept.

Please consider a native means to make these backups and allow remote restore.

**Comment by quickmic** [comment]
Yes, I will but takes some time. It's not on top of my list.

**Comment by quickmic** [comment]
I rewrote the backup/restore function in next-gen plugin. Works more or less same as you scripted in bash.

**Comment by nomandera** [comment]
I have set up a virtual test environment for this using LibreELEC 10 on VMware.

I am however unsure how this actually works since the GUI points to the [wiki ](https://github.com/MediaBrowser/plugin.video.emby/wiki/create-and-restore-from-backup) but that page clearly predates any enhancemnts.

Do you have any more info so that I can put some effort into testing this?

**Comment by nomandera** [comment]
Just for completeness this thread is missing a key detail.

`plugin.video.emby/settings.xml`

exists in every Kodi profile and contains an element such as 

```
<settings>
    <setting id="LastIncrementalSync" value="2022-03-19T23:01:45z" />
```

Without capturing and updating this element the restored client will use whatever value it already has, which in the case of an image restore, could be vastly out of date and will cause the client to perform a needless extended sync.
