### ISSUE TITLE
Couldn't extract filename from movies

### ISSUE THREAD

**Issue by gfjardim** [MediaBrowser/plugin.video.emby#80]
Hi. I'm the author of a subtitle service for Kodi (Legendas.TV), and I'm having a little trouble in getting the filename if using HTTP to stream any content.

If I search a subtitle of a tv show episode, InfoLabel "Player.Filenameandpath" will show something like `plugin://plugin.video.emby.tvshows/<hash>/?dbid=2598&mode=play&id=<hash>&filename=The.Affair.S03E10.PROPER.720p.HDTV.x264-AVS.mkv`. If I try to stream a movie, a completely different path is restrieved: `https://<IP>/Videos/<hash>/master.m3u8?MediaSourceId=<hash>&VideoCodec=h264&AudioCodec=ac3&MaxAudioChannels=6&deviceId=<hash>&VideoBitrate=3200000&AudioStreamIndex=1&AudioBitrate=384000`.

Is it feasible to add the filename as the last parameter in the second example, allowing me to extract the filename?

**Comment by im85288** [comment]
Hi, no the second example contains the parameters that the server needs to stream the file.

What I think we could do is to set a window property, for example 

window(home).property(embyfilename)

That you could check when needed.

Would that work for you?

**Comment by im85288** [comment]
I took the liberty of setting a window home property called "embyfilename" as mentioned above. This is included in version 2.3.42

I will set this to closed, but if you have issues feel free to re-open or create a new issue.

**Comment by faush01** [comment]
I am not sure file name is going to help you much.

A lot of people's file names are just junk, 1244.mkv, it is the parent directory NE the server uses most of the time for itentification.

Also in that case of playback via http a lot of people's paths will be local paths to the server and not accessible from the client so you won't be able to get access to the path directly if you need that.

If you are just looking for the name of the item playing it might be better to use the name of the item from the.library instead of the file name.
